filter:
    excluded_paths:
        - '3rdparty/*'
        - 'js/soundmanager2*'
        - 'js/bar*'
        - 'js/berniecode*'
        - 'js/jquery*'
        - 'js/360player*'          

imports:
    - javascript
    - php
